- Загрузить данные отзывов о перелетах
- Сделать кодировщик для целевой переменной
- Для текстовых столбцов сделать преобразователь, отдельно кодирующий порядковые и категориальные признаки
- Выполнить поиск по сетке параметра количество оценщиков в ансамбле, максимальная глубина дерева, количество признаков для разбиения
- Оценить точность на тестовой выборке (задана в отдельном файле)
- Показать какие признаки важны. TOP3 наиболее важных, TOP3 наименее важных

In [32]:
import numpy as np
import pandas as pd

In [33]:
data = pd.read_csv('train.csv', sep=',')

In [34]:
data.tail(5)

line num     id  Gender      Customer Type  Age   Type of Travel  \
103899    103899  94171  Female  disloyal Customer   23  Business travel   
103900    103900  73097    Male     Loyal Customer   49  Business travel   
103901    103901  68825    Male  disloyal Customer   30  Business travel   
103902    103902  54173  Female  disloyal Customer   22  Business travel   
103903    103903  62567    Male     Loyal Customer   27  Business travel   

           Class  Flight Distance  Inflight wifi service  \
103899       Eco              192                      2   
103900  Business             2347                      4   
103901  Business             1995                      1   
103902       Eco             1000                      1   
103903  Business             1723                      1   

        Departure/Arrival time convenient  ...  Inflight entertainment  \
103899                                  1  ...                       2   
103900                                  4  ...                       5   
103901                                  1  ...                       4   
103902                                  1  ...                       1   
103903                                  3  ...                       1   

        On-board service  Leg room service  Baggage handling  Checkin service  \
103899                 3                 1                 4                2   
103900                 5                 5                 5                5   
103901                 3                 2                 4                5   
103902                 4                 5                 1                5   
103903                 1                 1                 4                4   

        Inflight service  Cleanliness  Departure Delay in Minutes  \
103899                 3            2                           3   
103900                 5            4                           0   
103901                 5            4                           7   
103902                 4            1                           0   
103903                 3            1                           0   

        Arrival Delay in Minutes             satisfaction  
103899                       0.0  neutral or dissatisfied  
103900                       0.0                satisfied  
103901                      14.0  neutral or dissatisfied  
103902                       0.0  neutral or dissatisfied  
103903                       0.0  neutral or dissatisfied  

[5 rows x 25 columns]

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 25 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   line num                           103904 non-null  int64  
 1   id                                 103904 non-null  int64  
 2   Gender                             103904 non-null  object 
 3   Customer Type                      103904 non-null  object 
 4   Age                                103904 non-null  int64  
 5   Type of Travel                     103904 non-null  object 
 6   Class                              103904 non-null  object 
 7   Flight Distance                    103904 non-null  int64  
 8   Inflight wifi service              103904 non-null  int64  
 9   Departure/Arrival time convenient  103904 non-null  int64  
 10  Ease of Online booking             103904 non-null  int64  
 11  Gate location                      1039

In [36]:
nullrows = data[data['Arrival Delay in Minutes'].isnull()].index
for idx in nullrows:
    data.loc[idx, 'Arrival Delay in Minutes'] = data.loc[idx, 'Departure Delay in Minutes']

In [37]:
# data.tail(5)

line num     id  Gender      Customer Type  Age   Type of Travel  \
103899    103899  94171  Female  disloyal Customer   23  Business travel   
103900    103900  73097    Male     Loyal Customer   49  Business travel   
103901    103901  68825    Male  disloyal Customer   30  Business travel   
103902    103902  54173  Female  disloyal Customer   22  Business travel   
103903    103903  62567    Male     Loyal Customer   27  Business travel   

           Class  Flight Distance  Inflight wifi service  \
103899       Eco              192                      2   
103900  Business             2347                      4   
103901  Business             1995                      1   
103902       Eco             1000                      1   
103903  Business             1723                      1   

        Departure/Arrival time convenient  ...  Inflight entertainment  \
103899                                  1  ...                       2   
103900                                  4  ...                       5   
103901                                  1  ...                       4   
103902                                  1  ...                       1   
103903                                  3  ...                       1   

        On-board service  Leg room service  Baggage handling  Checkin service  \
103899                 3                 1                 4                2   
103900                 5                 5                 5                5   
103901                 3                 2                 4                5   
103902                 4                 5                 1                5   
103903                 1                 1                 4                4   

        Inflight service  Cleanliness  Departure Delay in Minutes  \
103899                 3            2                           3   
103900                 5            4                           0   
103901                 5            4                           7   
103902                 4            1                           0   
103903                 3            1                           0   

        Arrival Delay in Minutes             satisfaction  
103899                       0.0  neutral or dissatisfied  
103900                       0.0                satisfied  
103901                      14.0  neutral or dissatisfied  
103902                       0.0  neutral or dissatisfied  
103903                       0.0  neutral or dissatisfied  

[5 rows x 25 columns]

In [38]:
data = data.drop(labels=['line num', 'id'], axis=1)

In [46]:
data.head(5)

Gender      Customer Type  Age   Type of Travel     Class  Flight Distance  \
0    Male     Loyal Customer   13  Personal Travel  Eco Plus              460   
1    Male  disloyal Customer   25  Business travel  Business              235   
2  Female     Loyal Customer   26  Business travel  Business             1142   
3  Female     Loyal Customer   25  Business travel  Business              562   
4    Male     Loyal Customer   61  Business travel  Business              214   

   Inflight wifi service  Departure/Arrival time convenient  \
0                      3                                  4   
1                      3                                  2   
2                      2                                  2   
3                      2                                  5   
4                      3                                  3   

   Ease of Online booking  Gate location  ...  Seat comfort  \
0                       3              1  ...             5   
1                       3              3  ...             1   
2                       2              2  ...             5   
3                       5              5  ...             2   
4                       3              3  ...             5   

   Inflight entertainment  On-board service  Leg room service  \
0                       5                 4                 3   
1                       1                 1                 5   
2                       5                 4                 3   
3                       2                 2                 5   
4                       3                 3                 4   

   Baggage handling  Checkin service  Inflight service  Cleanliness  \
0                 4                4                 5            5   
1                 3                1                 4            1   
2                 4                4                 4            5   
3                 3                1                 4            2   
4                 4                3                 3            3   

   Departure Delay in Minutes  Arrival Delay in Minutes  
0                          25                      18.0  
1                           1                       6.0  
2                           0                       0.0  
3                          11                       9.0  
4                           0                       0.0  

[5 rows x 22 columns]

In [40]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [41]:
y = le.fit_transform(data['satisfaction'])
print(list(le.classes_))
print(y)

['neutral or dissatisfied', 'satisfied']
[0 0 1 ... 0 0 0]


In [42]:
data = data.drop(['satisfaction'], axis=1)

In [43]:
X2 = data.select_dtypes(include=[object])
X2.head(3)

Gender      Customer Type   Type of Travel     Class
0    Male     Loyal Customer  Personal Travel  Eco Plus
1    Male  disloyal Customer  Business travel  Business
2  Female     Loyal Customer  Business travel  Business

In [47]:
columnsToEncode = ['Gender','Customer Type','Type of Travel']
mlb = preprocessing.OrdinalEncoder()
dd0 = mlb.fit_transform(data[columnsToEncode])
print(dd0)

[[1. 0. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 ...
 [1. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
