In [1]:
import numpy as np
import pandas as p

In [2]:
data = p.read_csv('train.csv', sep=',')

In [3]:
data.head()

line num      id  Gender      Customer Type  Age   Type of Travel  \
0         0   70172    Male     Loyal Customer   13  Personal Travel   
1         1    5047    Male  disloyal Customer   25  Business travel   
2         2  110028  Female     Loyal Customer   26  Business travel   
3         3   24026  Female     Loyal Customer   25  Business travel   
4         4  119299    Male     Loyal Customer   61  Business travel   

      Class  Flight Distance  Inflight wifi service  \
0  Eco Plus              460                      3   
1  Business              235                      3   
2  Business             1142                      2   
3  Business              562                      2   
4  Business              214                      3   

   Departure/Arrival time convenient  ...  Inflight entertainment  \
0                                  4  ...                       5   
1                                  2  ...                       1   
2                                  2  ...                       5   
3                                  5  ...                       2   
4                                  3  ...                       3   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 4                 3                 4                4   
1                 1                 5                 3                1   
2                 4                 3                 4                4   
3                 2                 5                 3                1   
4                 3                 4                 4                3   

   Inflight service  Cleanliness  Departure Delay in Minutes  \
0                 5            5                          25   
1                 4            1                           1   
2                 4            5                           0   
3                 4            2                          11   
4                 3            3                           0   

   Arrival Delay in Minutes             satisfaction  
0                      18.0  neutral or dissatisfied  
1                       6.0  neutral or dissatisfied  
2                       0.0                satisfied  
3                       9.0  neutral or dissatisfied  
4                       0.0                satisfied  

[5 rows x 25 columns]

In [4]:
data.shape

(103904, 25)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 25 columns):
line num                             103904 non-null int64
id                                   103904 non-null int64
Gender                               103904 non-null object
Customer Type                        103904 non-null object
Age                                  103904 non-null int64
Type of Travel                       103904 non-null object
Class                                103904 non-null object
Flight Distance                      103904 non-null int64
Inflight wifi service                103904 non-null int64
Departure/Arrival time convenient    103904 non-null int64
Ease of Online booking               103904 non-null int64
Gate location                        103904 non-null int64
Food and drink                       103904 non-null int64
Online boarding                      103904 non-null int64
Seat comfort                         103904 non-null int64


Перетираем поля Arrival Delay со значениями null значением из поля Departure Delay

In [6]:
nullrows = data[data['Arrival Delay in Minutes'].isnull()].index
for idx in nullrows:
    data.loc[idx, 'Arrival Delay in Minutes'] = data.loc[idx, 'Departure Delay in Minutes']

In [7]:
data = data.drop(['line num', 'id'], axis=1)

In [8]:
targets = data.groupby('satisfaction').size()/len(data)
print(targets)

satisfaction
neutral or dissatisfied    0.566667
satisfied                  0.433333
dtype: float64


In [9]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [10]:
y = le.fit_transform(data['satisfaction'])
print(list(le.classes_))
print(y)

['neutral or dissatisfied', 'satisfied']
[0 0 1 ... 0 0 0]


In [11]:
data = data.drop(['satisfaction'], axis=1)

In [12]:
X2 = data.select_dtypes(include=[object])
X2.head(3)

Gender      Customer Type   Type of Travel     Class
0    Male     Loyal Customer  Personal Travel  Eco Plus
1    Male  disloyal Customer  Business travel  Business
2  Female     Loyal Customer  Business travel  Business

In [13]:
columnsToEncode = data.select_dtypes(include=[object]).columns.values

In [37]:
mlb = preprocessing.OrdinalEncoder()
dd0 = mlb.fit_transform(data[['Gender','Customer Type','Type of Travel']])
print(dd0)

[[1. 0. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 ...
 [1. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [38]:
data[['Gender','Customer Type','Type of Travel']] = p.DataFrame(dd0)

In [39]:
data.head()

Gender  Customer Type  Age  Type of Travel     Class  Flight Distance  \
0     1.0            0.0   13             1.0  Eco Plus              460   
1     1.0            1.0   25             0.0  Business              235   
2     0.0            0.0   26             0.0  Business             1142   
3     0.0            0.0   25             0.0  Business              562   
4     1.0            0.0   61             0.0  Business              214   

   Inflight wifi service  Departure/Arrival time convenient  \
0                      3                                  4   
1                      3                                  2   
2                      2                                  2   
3                      2                                  5   
4                      3                                  3   

   Ease of Online booking  Gate location  ...  Leg room service  \
0                       3              1  ...                 3   
1                       3              3  ...                 5   
2                       2              2  ...                 3   
3                       5              5  ...                 5   
4                       3              3  ...                 4   

   Baggage handling  Checkin service  Inflight service  Cleanliness  \
0                 4                4                 5            5   
1                 3                1                 4            1   
2                 4                4                 4            5   
3                 3                1                 4            2   
4                 4                3                 3            3   

   Departure Delay in Minutes  Arrival Delay in Minutes  Business  Eco  \
0                          25                      18.0       0.0  0.0   
1                           1                       6.0       1.0  0.0   
2                           0                       0.0       1.0  0.0   
3                          11                       9.0       1.0  0.0   
4                           0                       0.0       1.0  0.0   

   Eco Plus  
0       1.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 25 columns]

In [40]:
ohe = preprocessing.OneHotEncoder()
dd = ohe.fit_transform(data['Class'].values.reshape(-1, 1)).toarray()
feature_labels = ohe.categories_
feature_labels = np.concatenate(feature_labels)
print(feature_labels)

['Business' 'Eco' 'Eco Plus']


In [41]:
data[feature_labels] = p.DataFrame(dd)

In [42]:
data.head()

Gender  Customer Type  Age  Type of Travel     Class  Flight Distance  \
0     1.0            0.0   13             1.0  Eco Plus              460   
1     1.0            1.0   25             0.0  Business              235   
2     0.0            0.0   26             0.0  Business             1142   
3     0.0            0.0   25             0.0  Business              562   
4     1.0            0.0   61             0.0  Business              214   

   Inflight wifi service  Departure/Arrival time convenient  \
0                      3                                  4   
1                      3                                  2   
2                      2                                  2   
3                      2                                  5   
4                      3                                  3   

   Ease of Online booking  Gate location  ...  Leg room service  \
0                       3              1  ...                 3   
1                       3              3  ...                 5   
2                       2              2  ...                 3   
3                       5              5  ...                 5   
4                       3              3  ...                 4   

   Baggage handling  Checkin service  Inflight service  Cleanliness  \
0                 4                4                 5            5   
1                 3                1                 4            1   
2                 4                4                 4            5   
3                 3                1                 4            2   
4                 4                3                 3            3   

   Departure Delay in Minutes  Arrival Delay in Minutes  Business  Eco  \
0                          25                      18.0       0.0  0.0   
1                           1                       6.0       1.0  0.0   
2                           0                       0.0       1.0  0.0   
3                          11                       9.0       1.0  0.0   
4                           0                       0.0       1.0  0.0   

   Eco Plus  
0       1.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 25 columns]

In [43]:
data = data.drop(['Class'], axis=1)

In [44]:
data.head()

Gender  Customer Type  Age  Type of Travel  Flight Distance  \
0     1.0            0.0   13             1.0              460   
1     1.0            1.0   25             0.0              235   
2     0.0            0.0   26             0.0             1142   
3     0.0            0.0   25             0.0              562   
4     1.0            0.0   61             0.0              214   

   Inflight wifi service  Departure/Arrival time convenient  \
0                      3                                  4   
1                      3                                  2   
2                      2                                  2   
3                      2                                  5   
4                      3                                  3   

   Ease of Online booking  Gate location  Food and drink  ...  \
0                       3              1               5  ...   
1                       3              3               1  ...   
2                       2              2               5  ...   
3                       5              5               2  ...   
4                       3              3               4  ...   

   Leg room service  Baggage handling  Checkin service  Inflight service  \
0                 3                 4                4                 5   
1                 5                 3                1                 4   
2                 3                 4                4                 4   
3                 5                 3                1                 4   
4                 4                 4                3                 3   

   Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  \
0            5                          25                      18.0   
1            1                           1                       6.0   
2            5                           0                       0.0   
3            2                          11                       9.0   
4            3                           0                       0.0   

   Business  Eco  Eco Plus  
0       0.0  0.0       1.0  
1       1.0  0.0       0.0  
2       1.0  0.0       0.0  
3       1.0  0.0       0.0  
4       1.0  0.0       0.0  

[5 rows x 24 columns]

In [45]:
data.corr()

Gender  Customer Type       Age  \
Gender                             1.000000      -0.031732  0.008928   
Customer Type                     -0.031732       1.000000 -0.281674   
Age                                0.008928      -0.281674  1.000000   
Type of Travel                     0.006909      -0.308333 -0.048524   
Flight Distance                    0.005828      -0.225200  0.099461   
Inflight wifi service              0.008974      -0.007543  0.017859   
Departure/Arrival time convenient  0.009142      -0.206869  0.038125   
Ease of Online booking             0.006951      -0.019509  0.024842   
Gate location                      0.000333       0.006078 -0.001330   
Food and drink                     0.005772      -0.059454  0.023000   
Online boarding                   -0.042260      -0.189262  0.208939   
Seat comfort                      -0.026502      -0.159484  0.160277   
Inflight entertainment             0.006117      -0.109930  0.076444   
On-board service                   0.008156      -0.056560  0.057594   
Leg room service                   0.031798      -0.047868  0.040583   
Baggage handling                   0.037391       0.024723 -0.047529   
Checkin service                    0.010563      -0.032177  0.035482   
Inflight service                   0.039410       0.022670 -0.049427   
Cleanliness                        0.006505      -0.083613  0.053611   
Departure Delay in Minutes         0.002935       0.004036 -0.010152   
Arrival Delay in Minutes           0.000802       0.004459 -0.012137   
Business                           0.010634      -0.085601  0.138939   
Eco                               -0.005295       0.118694 -0.132551   
Eco Plus                          -0.010351      -0.062967 -0.013376   

                                   Type of Travel  Flight Distance  \
Gender                                   0.006909         0.005828   
Customer Type                           -0.308333        -0.225200   
Age                                     -0.048524         0.099461   
Type of Travel                           1.000000        -0.267344   
Flight Distance                         -0.267344         1.000000   
Inflight wifi service                   -0.105085         0.007131   
Departure/Arrival time convenient        0.259763        -0.020043   
Ease of Online booking                  -0.133511         0.065717   
Gate location                           -0.030700         0.004793   
Food and drink                          -0.063439         0.056994   
Online boarding                         -0.224803         0.214869   
Seat comfort                            -0.124399         0.157333   
Inflight entertainment                  -0.148199         0.128740   
On-board service                        -0.056543         0.109526   
Leg room service                        -0.138803         0.133916   
Baggage handling                        -0.031321         0.063184   
Checkin service                          0.016751         0.073072   
Inflight service                        -0.022599         0.057540   
Cleanliness                             -0.079207         0.093149   
Departure Delay in Minutes              -0.005432         0.002158   
Arrival Delay in Minutes                -0.005086        -0.002154   
Business                                -0.552125         0.466896   
Eco                                      0.500938        -0.404493   
Eco Plus                                 0.102775        -0.123674   

                                   Inflight wifi service  \
Gender                                          0.008974   
Customer Type                                  -0.007543   
Age                                             0.017859   
Type of Travel                                 -0.105085   
Flight Distance                                 0.007131   
Inflight wifi service                           1.000000   
Departure/Arrival time convenient               0.343845   
Ease 