In [1]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit_transform([[1, 2], [np.nan, 3], [7, 6]])

array([[1., 2.],
       [4., 3.],
       [7., 6.]])

In [2]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)
enc.categories_

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]

In [4]:
enc.transform([['Female', 1], ['Male', 1]])

array([[0., 0.],
       [1., 0.]])

In [5]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [26]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
oe.fit_transform(np.array(['red','blue','red', 'green']).reshape(-1, 1))

array([[2.],
       [0.],
       [2.],
       [1.]])

In [21]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
dd = ohe.fit_transform(np.array(['red','blue','red', 'green']).reshape(-1, 1))
print(dd.toarray())

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
