In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from plot_region import *

In [2]:
#на примере только двух классов
iris = datasets.load_iris()
X = iris.data[:100, [0, 2]]
y = iris.target[:100]

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=12)

In [4]:
clr = LogisticRegression(multi_class='auto',solver='liblinear')
clr.fit(X_train, y_train) 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [5]:
print(clr.predict(X_test[:3]))
print((y_test[:3]))

[0 0 1]
[0 0 1]


Предсказание вероятностей для первых трех экземпляров из тестовой выборки

In [6]:
np.set_printoptions(suppress=True)
clr.predict_proba(X_test[:3])

array([[0.95794708, 0.04205292],
       [0.93344088, 0.06655912],
       [0.04284752, 0.95715248]])

In [7]:
clr.predict_proba(X_test[:3]).sum()

3.0

Рассчитаем вероятность для первого тестового образца. Вводим функцию сигмоиды

In [8]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [9]:
example = X_test[:3]
print(example)

[[5.1 1.4]
 [4.5 1.3]
 [5.8 4. ]]


У натренированного классификатора забираем веса

In [10]:
print(clr.coef_)#w1, w2,...
print(clr.intercept_)#w0

[[-1.26470962  2.73749054]]
[-0.5083314]


Вероятность принадлежности классу 
sigmoid(coef_[0]* x[0]+coef_[1]* x[1]+intercept_)

In [11]:
for x in example:
    net_input = np.dot(x,clr.coef_.T) + clr.intercept_
    print(sigmoid(net_input))

[0.04205292]
[0.06655912]
[0.95715248]


In [12]:
clr.predict_proba(example)

array([[0.95794708, 0.04205292],
       [0.93344088, 0.06655912],
       [0.04284752, 0.95715248]])